name: Code Verification

on:
  workflow_call:
  push:
    branches: "**"

jobs:
  check_linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint code
        run: pnpm format:check

  call-testing-container:
    strategy:
      fail-fast: false
      matrix:
        shard_instance: [1, 2, 3, 4]
    uses: ./.github/workflows/testing-container.yml
    secrets: inherit
    with:
      shard_instance: ${{ matrix.shard_instance }}
      max_shards: 4
