name: Deploy to Development Server

on:
  workflow_dispatch:

jobs:
  shared-jobs:
    uses: ./.github/workflows/code-verification.yml
    secrets: inherit

  deploy:
    needs: shared-jobs
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to development server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            cd Stuns-Aterbrukslabbet/
            git checkout ${{ github.ref_name }}
            git fetch origin ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}
            pnpm i --frozen-lockfile
            pnpm build
            sudo shutdown -r +1 "Rebooting in 1 minute"
